"""Shared instruction fragments for strategy prompt templates."""

from .instructions_tikz import (  # noqa: F401
    PLANNER_INSTRUCTIONS,
    RAW_TIKZ_INSTRUCTIONS,
    PLAN_CODER_TIKZ_INSTRUCTIONS,
    DRAFT_INSTRUCTIONS,
    CODE_FROM_PLAN_INSTRUCTIONS,
    REVISION_PROMPT,
    STRUCTURED_REFINE_PROMPT,
    REVISION_INSTRUCTIONS,
    REVISION_FORCE_INSTRUCTIONS,
    STRUCTURED_REFINE_INSTRUCTIONS,
)
from .instructions_structured import STRUCTURED_STRATEGY_IR_INSTRUCTIONS  # noqa: F401
from .instructions_recipe import (  # noqa: F401
    RECIPE_SELECTION_SYSTEM,
    RECIPE_GENERATION_SYSTEM,
    RECIPE_DSL_QUICK_REF,
)
