"""Progressive tools strategy — 4-phase incremental diagram construction.

Re-exports all public names from sub-modules for backward compatibility.
"""

from .state import (  # noqa: F401
    DiagramState,
    ProgressiveToolsRunResult,
    compress_tool_history,
    def_references,
    cascade_remove,
    MAX_REPAIR_CYCLES,
    KEEP_RECENT,
)
from ir.refs import _REF_FIELDS, _NON_REF_FIELDS  # noqa: F401  (re-exported for backward compat)
from .handlers_construction import (  # noqa: F401
    handle_init_diagram,
    handle_add_point_fixed,
    handle_add_point_free,
    handle_add_point_on,
    handle_add_point_midpoint,
    handle_add_point_between,
    handle_add_point_foot,
    handle_add_point_rotate,
    handle_add_point_reflect,
    handle_add_point_triangle_center,
    handle_add_point_intersection,
    handle_add_segment,
    handle_add_ray,
    handle_add_line_through,
    handle_add_line_parallel_through,
    handle_add_line_perp_through,
    handle_add_line_angle_bisector,
    handle_add_line_tangent,
    handle_add_circle_center_point,
    handle_add_circle_center_radius,
    handle_add_circle_through3,
    handle_add_triangle,
    handle_add_polygon,
    handle_add_polygon_exterior,
    handle_remove_definition,
    handle_finalize_construction,
)
from .handlers_checks import (  # noqa: F401
    check_tool_names_for_state,
    handle_add_distinct_points_check,
    handle_add_distinct_objects_check,
    handle_add_collinear_check,
    handle_add_non_collinear_check,
    handle_add_parallel_check,
    handle_add_not_parallel_check,
    handle_add_perpendicular_check,
    handle_add_contains_check,
    handle_add_not_contains_check,
    handle_add_right_angle_check,
    handle_add_angle_equal_check,
    handle_add_equal_length_check,
    handle_add_ratio_equal_check,
    handle_add_similar_triangles_check,
    handle_add_tangent_check,
    handle_add_same_side_check,
    handle_add_opposite_side_check,
    handle_finalize_checks,
)
from .handlers_presentation import (  # noqa: F401
    presentation_tool_names_for_state,
    handle_draw,
    handle_draw_points,
    handle_fill,
    handle_mark_angles,
    handle_mark_right_angles,
    handle_mark_segments,
    handle_label_point,
    handle_label_angle,
    handle_label_segment,
    handle_finalize_render,
)
from .strategy import (  # noqa: F401
    ProgressiveToolsStrategy,
    _build_canvas_agent,
    _build_construction_agent,
    _build_checks_agent,
    _build_presentation_agent,
    _state_summary,
)
