"""Python fluent API surface for the geometry construction pipeline (Phase 1a).

Re-exports handles and op functions so callers (and the stub generator) have
one place to introspect the public surface.
"""
from geometry_diagrams.pydsl.api import altitude, angle_bisector, arc, canvas, centroid, circle, circumcircle, dilate_point, draw, draw_points, ellipse, fill, foot_of_perpendicular, incircle, intersection, label_text, line_through, mark_angle, mark_equal, mark_parallel, mark_proportional, mark_right_angle, median, parallel_through, perpendicular_bisector, perpendicular_through, point, point_on, polygon, polyline, ray, rectangle, reflect_point, regular_polygon, regular_sectors, rotate_point, sector, segment, tangent_line, triangle, walk
from geometry_diagrams.pydsl.handles import AngleRef, Altitude, Arc, Circle, Ellipse, Line, Median, PerpendicularBisectorLine, Point, Polygon, Polyline, Ray, Sector, Segment, Triangle

__all__ = [
    "point",
    "line_through",
    "ray",
    "triangle",
    "polygon",
    "polyline",
    "regular_polygon",
    "regular_sectors",
    "rectangle",
    "segment",
    "tangent_line",
    "circumcircle",
    "incircle",
    "circle",
    "ellipse",
    "arc",
    "sector",
    "intersection",
    "median",
    "altitude",
    "angle_bisector",
    "centroid",
    "foot_of_perpendicular",
    "parallel_through",
    "perpendicular_bisector",
    "perpendicular_through",
    "canvas",
    "mark_angle",
    "mark_equal",
    "mark_parallel",
    "mark_proportional",
    "mark_right_angle",
    "draw",
    "draw_points",
    "fill",
    "label_text",
    "point_on",
    "rotate_point",
    "reflect_point",
    "dilate_point",
    "walk",
    "Point",
    "Line",
    "Ray",
    "Segment",
    "Triangle",
    "Polygon",
    "Polyline",
    "Circle",
    "Ellipse",
    "Arc",
    "Sector",
    "Median",
    "PerpendicularBisectorLine",
    "Altitude",
    "AngleRef",
]
